services:
  lomonosov_streamlit:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecstatic_mclaren
    env_file:
      - .env-prod  
    ports:
      - "8501:8501" 
